Update README with correct installation instructions
crossplane-contrib/provider-kubernetes pull request #239
Opened 2024-05-08 05:53 UTC by scubbo

### Description of your changes

Fixes #233 

I have:

- [X] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.
  - Well, I _did_ - but I got `make: *** No rule to make target `reviewable'.  Stop.`. Similar error for just `make reviewable`.

### How has this code been tested

Confirmed that the new instructions installed a Provider which did not error-out.

[contribution process]: https://git.io/fj2m9

2024-05-08 08:22 UTC, jbw976 requested changes
awesome @scubbo, thanks for updating these very out of date steps! 😊 

There's more to the readme (e.g. local dev steps) that we'll want to update sometime as well, but this is the critical part to address that is broadly applicable for all users of this provider, so we can follow up in a later PR on the other stuff.

Just one correction to make to remove `kubectl` and then we can merge this - I have tested these updates otherwise and they are working good for me!

2024-05-08 08:22 UTC, jbw976 commented on README.md
> +kubectl crossplane xpkg install provider xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.13.0
The [Crossplane CLI](https://docs.crossplane.io/latest/cli/) is no longer a plugin for `kubectl`, so we can remove the `kubectl` from this line as well. 

```suggestion
crossplane xpkg install provider xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.13.0
```

2024-05-09 06:40 UTC, jbw976 approved these changes
Looks good to me now, thanks again for making this improvement @scubbo!! 💪

2024-05-09 06:41 UTC, merged

2024-05-11 22:15 UTC, scubbo commented
Thanks for the help :)